# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# https://docs.cilium.io/en/stable/helm-reference/
# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cilium:
  operator:
    skipCRDCreation: true
    replicas: 1
  envoy:
    enabled: false
  hubble:
    enabled: false
  kubeProxyReplacement: true
  ipv4:
    enabled: true
  ipv6:
    enabled: false
